### ISSUE TITLE
Bad documentation on DMap

### ISSUE THREAD

**Issue by spl** [mokus0/dependent-map#1]
There are a few errors on the Haddock docs for `DMap`.
1. `Data.Dependent.Tag` doesn't seem to exist.
2. The documentation refers to some `f` which I guess is supposed to be the `k` type parameter of `DMap`.

**Comment by mokus0** [comment]
Thanks for pointing these out.  Sorry not to reply sooner, I've been busy with a cross-country move and I currently am using a tablet as my sole computer, without a physical keyboard, which makes even minor code-related tasks quite a chore. Just wanted to let you know I'm not ignoring this.

**Comment by spl** [comment]
No problem. :) Good luck with the move.
