### ISSUE TITLE
Stop using hedge algorithms

### ISSUE THREAD

**Issue by treeowl** [mokus0/dependent-map#8]
The master branch of `containers` has switched from hedge algorithms to divide-and-conquer algorithms (often with pointer equality optimizations). These algorithms have recently been proven asymptotically optimal and my tests indicate that they're a good deal faster than the hedge algorithms. As an extra bonus, they're considerably simpler and harder to mess up. I suggest you use them here as well.

**Comment by mokus0** [comment]
If I'm not mistaken, your pull request (which I just merged) fixes this.  Thank you!
